version: '3.8'

services:
  extraction-server:
    build:
      context: ../..
      dockerfile: mcp_servers/extraction_server/Dockerfile
    container_name: doctracer-extraction-server
    volumes:
      - ../../data:/app/data
      - ../../output:/app/output
    environment:
      - PYTHONPATH=/app
    networks:
      - doctracer-network
    restart: unless-stopped

  prompt-server:
    build:
      context: ../..
      dockerfile: mcp_servers/prompt_server/Dockerfile
    container_name: doctracer-prompt-server
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - doctracer-network
    restart: unless-stopped

networks:
  doctracer-network:
    driver: bridge
